language: go

# safelist
branches:
  only:
  - master
  - travis

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get golang.org/x/tools/cmd/cover

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2

after_success:
  - chmod u+x .aggregate_coverage.sh
  - ./.aggregate_coverage.sh
  - bash <(curl -s https://codecov.io/bash)
  