language: go

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2

after_success:
  - ./.aggregate_coverage.sh
  - bash <(curl -s https://codecov.io/bash)
  